### ISSUE TITLE
Default Username / Password not working in latest image

### ISSUE THREAD

**Issue by elbarsal** [key-networks/ztncui-containerized#23]
It seems the default username / password (admin / password) are not working in the latest release. I went back to 1.2.5 and it worked again. Tested with both docker and podman.

**Comment by key-networks** [comment]
The new process for building and using this image is here: https://github.com/key-networks/ztncui-aio

Note that you need an environment file (example 'denv' is provided in the git repo) that specifies the password.  Let us know if this helps.

**Comment by changchichung** [comment]
@key-networks 
can you please update the readme how to pass "denv" ??
I can't get the correct login/password ...

**Comment by changchichung** [comment]
> @key-networks
> can you please update the readme how to pass "denv" ??
> I can't get the correct login/password ...

never mind , it's working now
I always thought denv was a typo  .....

**Comment by mmdjiji** [comment]
I think you need give some tips when first login with username `admin`, or that will be a trap for users. (Just a sincere suggestion)

**Comment by mmdjiji** [comment]
Of course I see the tips from repo `ztncui-aio` that you can use this command to check the default password:
```sh
cat /var/log/docker-ztncui.log
```
But it doesn't work.

**Comment by mmdjiji** [comment]
I finally solved by set an env variable `ZTNCUI_PASSWD=password` when the container be created.

**Comment by hugalafutro** [comment]
I am running into same issue even with the env variable.
```
sammael@vm-docker:~/docker/ztncui-aio$ docker-compose config
services:
  ztncui-aio:
    container_name: ztncui-aio
    environment:
      HTTPS_PORT: '3443'
      MYDOMAIN: ztncui.docker.test
      NODE_ENV: production
      ZTNCUI_PASSWD: password
    image: keynetworks/ztncui
    ports:
    - published: 3443
      target: 3443
    - published: 3180
      target: 3180
    volumes:
    - /home/sammael/docker/ztncui-aio/data/ztncui:/opt/key-networks/ztncui/etc:rw
    - /home/sammael/docker/ztncui-aio/data/zt1:/var/lib/zerotier-one:rw
version: '3.3'
```
trying logging in with `admin` / `password` I get `Authentication failed, please check your username and password.` Inside container:
```
sammael@vm-docker:~/docker/ztncui-aio$ docker exec -it ztncui-aio bash
root@dc17398c1384:/# cat /var/log/docker-ztncui.log
Set Your IP Address to continue.
If you don't do that, I will automatically detect.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0     46      0 --:--:-- --:--:-- --:--:--    46
YOUR IP: [REDACTED]
ZTNCUI ENV CONFIGURATION:
NODE_ENV=production
MYADDR=[REDACTED]
HTTP_PORT=3000
HTTPS_PORT=3443
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
Listening for HTTP requests on port 3000 on localhost
Listening for HTTPS requests on port 3443 on all interfaces
GET /login 200 154.345 ms - 2292
GET /bscss/bootstrap.min.css 200 3.503 ms - 121457
GET /stylesheets/style.css 200 0.994 ms - 2867
GET /jqjs/jquery.min.js 304 1.508 ms - -
GET /bsjs/bootstrap.min.js 304 1.292 ms - -
GET /images/key-logo.svg 304 0.556 ms - -
GET /fonts/glyphicons-halflings-regular.woff2 304 0.815 ms - -
POST /login 302 18.060 ms - 56
GET /login 200 1.509 ms - 2408
GET /bscss/bootstrap.min.css 200 1.789 ms - 121457
GET /stylesheets/style.css 200 1.085 ms - 2867
GET /jqjs/jquery.min.js 304 2.025 ms - -
GET /bsjs/bootstrap.min.js 304 1.645 ms - -
GET /images/key-logo.svg 304 0.840 ms - -
GET /fonts/glyphicons-halflings-regular.woff2 304 1.553 ms - -
GET / 200 24.070 ms - 1309
GET /bscss/bootstrap.min.css 200 2.754 ms - 121457
GET /stylesheets/style.css 200 2.500 ms - 2867
GET /bsjs/bootstrap.min.js 200 2.146 ms - 39680
GET /jqjs/jquery.min.js 200 1.892 ms - 88145
GET /images/key-logo.svg 200 0.716 ms - 3249
GET /fonts/glyphicons-halflings-regular.woff2 200 0.949 ms - 18028
GET /login 200 0.861 ms - 2292
```
where I don't see any mention of password. @mmdjiji could you by chance post exact steps how you made it work ?

**Comment by machsix** [comment]
Delete the volumes and recreate the docker container helps

**Comment by rupesh43210** [comment]
> I am running into same issue even with the env variable.
> 
> ```
> sammael@vm-docker:~/docker/ztncui-aio$ docker-compose config
> services:
>   ztncui-aio:
>     container_name: ztncui-aio
>     environment:
>       HTTPS_PORT: '3443'
>       MYDOMAIN: ztncui.docker.test
>       NODE_ENV: production
>       ZTNCUI_PASSWD: password
>     image: keynetworks/ztncui
>     ports:
>     - published: 3443
>       target: 3443
>     - published: 3180
>       target: 3180
>     volumes:
>     - /home/sammael/docker/ztncui-aio/data/ztncui:/opt/key-networks/ztncui/etc:rw
>     - /home/sammael/docker/ztncui-aio/data/zt1:/var/lib/zerotier-one:rw
> version: '3.3'
> ```
> 
> trying logging in with `admin` / `password` I get `Authentication failed, please check your username and password.` Inside container:
> 
> ```
> sammael@vm-docker:~/docker/ztncui-aio$ docker exec -it ztncui-aio bash
> root@dc17398c1384:/# cat /var/log/docker-ztncui.log
> Set Your IP Address to continue.
> If you don't do that, I will automatically detect.
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    13  100    13    0     0     46      0 --:--:-- --:--:-- --:--:--    46
> YOUR IP: [REDACTED]
> ZTNCUI ENV CONFIGURATION:
> NODE_ENV=production
> MYADDR=[REDACTED]
> HTTP_PORT=3000
> HTTPS_PORT=3443
> Warning: connect.session() MemoryStore is not
> designed for a production environment, as it will leak
> memory, and will not scale past a single process.
> Listening for HTTP requests on port 3000 on localhost
> Listening for HTTPS requests on port 3443 on all interfaces
> GET /login 200 154.345 ms - 2292
> GET /bscss/bootstrap.min.css 200 3.503 ms - 121457
> GET /stylesheets/style.css 200 0.994 ms - 2867
> GET /jqjs/jquery.min.js 304 1.508 ms - -
> GET /bsjs/bootstrap.min.js 304 1.292 ms - -
> GET /images/key-logo.svg 304 0.556 ms - -
> GET /fonts/glyphicons-halflings-regular.woff2 304 0.815 ms - -
> POST /login 302 18.060 ms - 56
> GET /login 200 1.509 ms - 2408
> GET /bscss/bootstrap.min.css 200 1.789 ms - 121457
> GET /stylesheets/style.css 200 1.085 ms - 2867
> GET /jqjs/jquery.min.js 304 2.025 ms - -
> GET /bsjs/bootstrap.min.js 304 1.645 ms - -
> GET /images/key-logo.svg 304 0.840 ms - -
> GET /fonts/glyphicons-halflings-regular.woff2 304 1.553 ms - -
> GET / 200 24.070 ms - 1309
> GET /bscss/bootstrap.min.css 200 2.754 ms - 121457
> GET /stylesheets/style.css 200 2.500 ms - 2867
> GET /bsjs/bootstrap.min.js 200 2.146 ms - 39680
> GET /jqjs/jquery.min.js 200 1.892 ms - 88145
> GET /images/key-logo.svg 200 0.716 ms - 3249
> GET /fonts/glyphicons-halflings-regular.woff2 200 0.949 ms - 18028
> GET /login 200 0.861 ms - 2292
> ```
> 
> where I don't see any mention of password. @mmdjiji could you by chance post exact steps how you made it work ?

Have the exact same issue. Trued deleting container and volumes many times, still no luck

**Comment by mmdjiji** [comment]
Don't do `cat /var/log/docker-ztncui.log`, just use the ENV VARIABLE!

**Comment by rgados** [comment]
docker run --env ZTNCUI_PASSWD=password --name ztncui -dp 3443:3443 keynetworks/ztncui

**Comment by pengxingyang02** [comment]
docker运行”docker run --env ZTNCUI_PASSWD=password --name ztncui -d -p 3443:3443 keynetworks/ztncui“来拉取下载即可。
